### ISSUE TITLE
Create a "Distance From Fire Station" Feature Set

### ISSUE THREAD

**Issue by ryangtanaka-org** [sfbrigade/datasci-firerisk#16]

**Comment by andirs** [comment]
The idea is, to get a complete list of all fire stations in San Francisco. This might be cool for visualization purposes as well and could be visualized on top of the model visualization. The next step is finding the closest fire department for each data point in the masterdf and storing the distance.

**Tasks:**
- [x] Web scrape addresses of SF fire stations
- [x] Retrieve geolocations in same style as masterdf
- [x] Calculate simple distance metric between points and find nearest fire station
- [x] Retrieve driving distance between points and nearest fire station *(pending API limits)*
- [x] Merge with existing masterdf

Happy about any comments, hints, questions.

**Comment by andirs** [comment]
Quick amend.

As suggested by Sam: OSRM could be used to compute driving distance.
- [x] Set-up OSRM backend
- [x] Use proxy of nearest haversine distance to route through local API
- [x] Prepare merge-ready csv file

In a live setting we could potentially set up an online instance of OSRM and perform any routing tasks 'on the go' as needed.
